//ESTADO PARA LOS PRODUCTOS
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';


//ESTADO PARA LOS PEDIDOS
export const SELECCIONAR_PRODUCTOS = 'SELECCIONAR_PRODUCTOS';

//GUARDAR PEDIDO
export const GUARGAR_PEDIDO = 'GUARGAR_PEDIDO';

//MOSTRAR RESUMEN
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
